### PR TITLE
Latest stable version I am using. Tested with ancient Unix machine.

### LINKED ISSUE #29: TerminatedReadAsync always hits timeout despite returning the terminator.
Here is what I am doing:

> serverResponse = Await telnet.TerminatedReadAsync("#", TimeSpan.FromMilliseconds(SocketTimeout))

After that there is a test of the serverResponse to look for text from the command I ran. The serverResponse contains all of the text since the last command, including the terminator character "#". How can the returned string contain the terminator while TerminatedReadAsync hit the timeout? 

(I've tested this and I know that the result has returned long before the timeout)

There are some characters returned after the terminator character "# " which further illustrates that the function doesn't return when expected. 

The characters after my terminator are:

> U+0008 : <control-0008> (BACKSPACE [BS])
> U+0008 : <control-0008> (BACKSPACE [BS])
> U+0020 : SPACE [SP]
> U+0020 : SPACE [SP]
> U+0008 : <control-0008> (BACKSPACE [BS])
> U+0008 : <control-0008> (BACKSPACE [BS])

### LINKED ISSUE #30: null exception on internalCancellation.Cancel
There exists the possibility that a cancel sent at the wrong time will cause a null exception. It happened to me while testing. 

 token.Register(() => this.internalCancellation.Cancel());

I have a solution that I will propose in an upcoming Pull Request.

### LINKED ISSUE #31: Method of Sending DONT\WONT can cause negotiation looping
The default state of all options is DONT\WONT. You are only supposed to reply on state change. We only want to turn on suppress go ahead and we can't support it being off. Therefore we should ignore Don't\Won't because that is the default state.
This helps avoid loops.
See RFC1143: https://tools.ietf.org/html/rfc1143

I have a solution that I will propose in an upcoming Pull Request.

### LINKED ISSUE #32: We don't handle common TELNET codes
The following codes should be handled instead of treated like printable characters.

From RFC854:

>          BELL (BEL)              7      Produces an audible or
>                                         visible signal (which does
>                                         NOT move the print head).
>          Back Space (BS)         8      Moves the print head one
>                                         character position towards
>                                         the left margin.
>          Horizontal Tab (HT)     9      Moves the printer to the
>                                         next horizontal tab stop.
>                                         It remains unspecified how
>                                         either party determines or
>                                         establishes where such tab
>                                         stops are located.
>          Vertical Tab (VT)       11     Moves the printer to the
>                                         next vertical tab stop.  It
>                                         remains unspecified how
>                                         either party determines or
>                                         establishes where such tab
>                                         stops are located.
>          Form Feed (FF)          12     Moves the printer to the top
>                                         of the next page, keeping
>                                         the same horizontal position.

http://www.rfc-editor.org/rfc/rfc854.txt

I have a solution that I will propose in an upcoming Pull Request.

### PR DESCRIPTION
**Pull request by A9G-Data-Droid**
I'm not sure if you would prefer a different pull request for each issue. I found and fixed other problems along the way. I figured I would give you all the code and let you decide what you want from it. This new version reliably speaks to my old friend HP-UX.

CHANGELOG:
BaseClient.cs IsTerminatorLocated fixes #29 
BaseClientCancellable.cs new method SendCancel fixes #30 
ByteStreamHandlerCancellable.cs new method SendCancel fixes #30 

ByteStreamHandler.cs fixes #31 and fixes #32
ADDED Subnegotiation for TerminalType and TerminalSpeed
ADDED Enough Debug writes to watch the option negotiation occur in real time.

ADDED ALL Telnet commands and options to Commands.cs Options.cs
(This allows me to translate incoming symbols to text while debugging.)

### CODE REVIEW

**Comment by A9G-Data-Droid** [comment]
You have a test called "WhenIacDont1ByteStreamShouldReturnEmptyAndReplyIacDont" which was erroneous behavior. The proper reply to DONT is WONT but according to rfc1143 you must remain silent when someone tells you DONT to an option that is already off. You would reply WONT if the option was on and you are turning it off. You would never reply DONT to DONT under any circumstances.

**Comment by A9G-Data-Droid** [comment]
You also have a test called "WhenIacDontSgaByteStreamShouldReturnEmptyAndReplyIacDo" which goes against the Telnet protocol:

> Where RFC 854 implies that the other side may reject a request to
>       enable an option, it means that you must accept such a rejection.

This means that you should never reply DO to a DONT. I understand that we can't operate in GO AHEAD mode so it makes sense that we would insist. With my current implementation it would ignore the request to DONT SGA. Due to the limitations of this library we should really be proactively pushing the DO SGA upon connect, like PuTTY does.

**Comment by 9swampy** [comment]
Thanks @A9G-Data-Droid you've been busy! Re the "erroneous" test I believe if you trace it all the way back that one will have been inherited from the https://www.codeproject.com/Articles/19071/Quick-tool-A-minimalistic-Telnet-library shoulders upon which this repository stands. I recall looking in to the specifications at the time but for the most part left it as inherited. IF it ain't broke and serves a purpose... and after all this is quite a way off a full implementation! Let me have a look at your proposal & consider the breaking change. Could you clarify what didn't work for you as it was; or is this just to bring behaviour more in line with the specification quoted? What's your view of the likelihood of negatively impacting existing users?

**Comment by A9G-Data-Droid** [comment]
I was experiencing negotiation failure with an old server that didn't expect the client to be irrational. The logon prompt was never presented because it was waiting for negotiation to end. By suppressing response to DONT\WONT we come in line with the RFCs and we also avoid loops. I would expect negotiations to go more smoothly now with a larger number of servers. I can't imagine a server that would prefer the old behavior but anything is possible... Each Telnet implementation is slightly different and the RFCs were written to create a system where that is possible. Everyone can be different and still communicate if they follow the rules. That's not saying my logic here is sound or without other new faults\bugs... All I know is that it makes sense to me and it works for me. I guess we need a variety of servers to test it against to be sure. You can run it against your servers with the debug flags on and watch the negotiation in the debug window or debug listener. (I have a debug listener that sends the whole conversation to a window that I can watch and save the text when I'm done)

The biggest risk I see with my new code is telling the server we are a VT100. This makes Unix happy but it could have side effects that I have not encountered. You could turn off the terminal type sub-negotiation if you don't like it. Do you know of a different terminal type that more closely matches the capabilities of this library?

NOTE: I found a workaround while testing. If I send a null char I can break out of negotiation and get a logon prompt. I don't know why this works.

**Comment by A9G-Data-Droid** [comment]
Ok, today I was able to fully test my Terminal Speed setting and it's great. Unix will default to 300 baud if you refuse to negotiate terminal speed. Now I tell it I'm a VT100 connected to a state of the art 38400 baud modem! This allows us to get on nicely at a good clip. I removed the erroneous tests so that this should pass the appveyor testing phase.

**Comment by 9swampy** [comment]
> I was experiencing negotiation failure with an old server that didn't expect the client to be irrational. 

Haha. No offence taken :-p

Your reasoning all sounds fair to me so far. I'm leaning towards deferring to your demonstrated knowledge and experience in this area; I don't claim to be an expert and i've a good feeling to taking on your suggestions following a quick review. I need to run some tests against my use cases and I'll suggest pushing out a beta version with the more risky elements first and see if anyone comes back with issues.

Could you fix protected void SendCanel() though? :)

**Comment by 9swampy** [comment]
Have a look at https://github.com/9swampy/Telnet/issues/14

What would you have done?

**Comment by A9G-Data-Droid** [comment]
Oh, I made one public and one protected... That's odd. Is there something else wrong with it I am missing? Should it be public?

PS - I don't understand why I am getting build errors from AppVeyor.

**Comment by A9G-Data-Droid** [comment]
On the matter of 14, the actual performance of WILL ECHO is non-trivial. I'm not sure why a Cisco device would require it. You can't just turn it on and walk away. You need to hold state variables and actually perform the echo...

This is the most concerning to me:
RFC857:
> It should be noted that if BOTH hosts enter the mode of echoing
>    characters transmitted by the other host, then any character
>    transmitted in either direction will be "echoed" back and forth
>    indefinitely.

https://tools.ietf.org/html/rfc857

**Comment by A9G-Data-Droid** [comment]
To answer the question more directly I think I would have required a full ECHO implementation before accepting a pull request.

**Comment by 9swampy** [comment]
SendCancel, not SendCanel

It's the NetStandard build that's failing; have you introduced anything that might not be in the NetStandard scope? Lots of the files are linked across multiple framework versions of the libraries; have you changed anything that has introduced a missing reference in another framework? Some files are shared but peppered with preprocessor directives; others are customised to the specific frameworks nuances. I get a headache from it sometimes too... Are you building the whole solution on your local machine?

Feels like you're agreeing on https://github.com/9swampy/Telnet/issues/14 ? I didn't like saying something was being switched on when it blatantly wasn't.

**Comment by A9G-Data-Droid** [comment]
Using VS2017 15.6.6 I did a clean and rebuild. I get 

> ========== Rebuild All: 7 succeeded, 0 failed, 0 skipped ==========

Yes. More code is required to close #14. The lack of echo support is an issue, even if it will never be fixed.

I'll poke around and push another commit.

**Comment by 9swampy** [comment]
My apologies. Ignore AppVeyor for now; it's not built since I added the NetStandard build yonks ago. It all builds and passes on my internal build server which is the publish stream. I should really look in to the AppVeyor config though too when I get a chance...

**Comment by A9G-Data-Droid** [comment]
Ok, I fixed the typo and now it says All checks have passed...

**Comment by 9swampy** [comment]
...and now it doesn't :) There are two builds on AppVeyor, one for CI that passes, and another to build release artefacts that fails a minute later - but I'm not using. Ignore it; I can't even see how to disable the build in the interim.

**Comment by 9swampy** [comment]
I'd missed the removal of the erroneous test. Could you add it back in please (in same location so deltas are easier) but update it to reflect the corrected behaviour proposed; alter the name appropriately. It's fine to fix behaviour but not at the expense of a lost test without replacement...

Put your ReleaseNotes in Telnet.nuspec too so you take credit when published.

**Comment by 9swampy** [comment]
Heh. For us old dogs, always new tricks :) The nuspec's just an xml attribute to put your notes in; no doubt you're up to that. Testing; you've never written one?!?! Heathen!!! From an evangelist... :) it'll be worth it

**Comment by A9G-Data-Droid** [comment]
Now it's really broken. I'm not sure what was supposed to happen here but the merge has failed.

**Pull request closed without merging**
