### PR TITLE
Remove deprecated LiteGuard dependency

### PR DESCRIPTION
**Pull request by bdovaz**
I have based this on the release/0.9.1 branch which is the one that I see has the most updated code.

LiteGuard package it's deprecated:

https://github.com/adamralph/liteguard

What I did was simply to move the Guard.cs class to the NetStandard project and reference it in the PrimS.Telnet project as it was already done with many other files.

### CODE REVIEW

**Comment by bdovaz** [comment]
@9swampy ping!

**Comment by 9swampy** [comment]
If you fix the failing tests you'd be making my life easy...

**Comment by bdovaz** [comment]
@9swampy But if you look at the error, it doesn't seem to have to do with tests but rather with msbuild command from appveyor:

https://github.com/9swampy/Telnet/blob/master/appveyor.CiBuild.yml

image

**Comment by 9swampy** [comment]
Didn't merge but the intent's included in the release 0.9.1 I've just pushed to Nuget.

Any problems, shout.

**Comment by bdovaz** [comment]
@9swampy If my changes to this PR are included in 0.9.1 you can close this PR if you want to avoid confusion.

Thanks.

**Pull request closed without merging**
