### PR TITLE
Added NetStandard .NET Core project, also supports .NET Framework 4.51

### PR DESCRIPTION
**Pull request by rweads0520**

### CODE REVIEW

**Comment by 9swampy** [comment]
Hi, I'm having to fire up a 2015 build agent and fiddle with internal Git setup for my team city to work with this but it's looking pretty good. Will revert as soon as I've validated & am able to publish.

**Comment by rweads0520** [comment]
Thanks for your response, and thanks for the code, was a big help in our
project! Although it will break backward compatibility, I'd still like to
add a separate ConnectAsync method to the client at some point soon, as I
believe the current method I've committed of starting a ConnectAsync in the
constructor and blocking the thread to wait for the connection to complete
has a potential to deadlock. In any case, hope you can use some or all of
what I did as a start for a .NET Core relelase.

Regards,
Robb

**Comment by 9swampy** [comment]
I rebased onto a bit of tidy up I'd worked on but hadn't merged in yet. Made sense to include it in your addition too. Merged in to Develop, all builds and tests on the incumbent implementations still pass so we're good I think. 

Would be great if you could verify it works for you in your use case for DotNet. 

@ngonzalezromero - would be great if you could check this works/replicates your use case too. @rweads0520 PR kept the incumbents intact so was easier for me to integrate.

**Comment by 9swampy** [comment]
...should have said before the IgnoreCommands stuff I'd like to look in to how it works with the other ports... and the version numbering I have been using GitVersion to complete automatically so need to see how well it plays with NetCore projects. Looks sensible, as does the suggestion to introduce ConnectAsync even if it breaks backwards compatibility. That is what pre-release-1.0.0.0's for... and @ngonzalezromero was having the same issue too.

**Comment by rweads0520** [comment]
Your develop branch builds and tests correctly for me, all looks good, have
tested on Windows 10 and Ubuntu 16.04. I do still have to run my
feature/IgnoreCommands changes to work for my use case. I haven't spent a
lot of time troubleshooting my issue, but it's likely a problem with the
telnet server I'm running against. It is an embedded BusyBox server on a
cable modem device, and although it is sending me telnet commands, when I
respond to them it appears to be trying to interpret the response as input
characters, and is causing the login to fail. As you probably saw,
feature/IgnoreCommands allows an option that will still read all commands
off of the stream, but will not respond to them. I don't know if this would
be of general use to others or not, and if I looked into the problem
further, I might find that there is a better solution.

**Comment by 9swampy** [comment]
Finally got some time to work with this the last couple of days; Having fun getting UnitTests working in NetStandard. See https://github.com/dotnet/cli/issues/5724. Don't suppose you've got a solution?

**Comment by 9swampy** [comment]
Spent the weekend playing with the new 2017 toys. Published at last. Thx for input.

**Comment by rweads0520** [comment]
Just moved to 2017 myself, liking it so far, especially for the .NET core
stuff. Glad you were able to get it published.

Robb

**Pull request closed without merging**
