### PR TITLE
Update LiteGuard + Fixes and performance boost

### LINKED ISSUE #34: token.register calls this.internalCancellation.Cancel()
token.Register(() => this.internalCancellation.Cancel());

What this says is "After we have received a cancel command, send a cancel command". I only noticed this because it throws a null exception. The null exception is due to the cancel command already being done.

I recommend removing this line altogether.

### PR DESCRIPTION
**Pull request by A9G-Data-Droid**
I went in to update LiteGuard and I ended up finding more things I wanted to change!

I'll try to explain the lines in my release notes here:

- Remove erroneous token.register Closes #34
I found that the token.register was set to run a cancel command which is backwards because token.register runs after a cancel command... This created a loop that was only broken by a null exception.

- Add cancel call to dispose
If we haven't cancelled by the time dispose rolls around we should ensure that all operations have been given the cancel signal.

- Increased read delay
The system clock is only accurate to 10-30ms. Most systems need 15ms to count a single tick using Thread.Sleep or Task.Delay.

- Created buffered write operations for all internal functions
This gave me a huge performance boost. I think it's because using .WriteByte makes a bunch of tiny packets, increasing the packet count and ACK wait times. By buffering the data and passing it all at once we get better performance at the TCP level. Less ACKs = less waiting.

- Added Window Size negotiation
This was the last thing my server was expecting. Unix servers expect at least 3 options to be passed by a dumb terminal: TerminalType, TerminalSpeed, and NAWS. 

- Added proactive SGA send
By telling the server that we want to suppress go ahead right up front we ensure that we don't get defaulted to GoAhead mode which isn't supported by this library, yet.

### CODE REVIEW

**Comment by sharyex** [comment]
> 
> 
> @A9G-Data-Droid cherry picked over to a feature branch and merged/published as a release candidate (https://www.nuget.org/packages/Telnet/0.9.0-beta0001) as opposed to accepting the PR & bumping the version to 0.9+ due to tbc incremental breaking changes introduced. Still need to review and confirm against my use cases but appreciating the contributions and would value wider feedback (looking at you @iftahb)

Can't authenticate using this branch, it seems random characters are added to the credentials.  
e.g. pass an username of "admin", and the server responds with "User ��admin does not exist."  
  
The same code works fine in 0.8.1. ASP.NET Core 2.1.

**Comment by A9G-Data-Droid** [comment]
What server are you connecting to?
And what are those three mystery characters?

Try pasting the characters directly in to here to get an explanation:
http://www.babelstone.co.uk/Unicode/whatisit.html

**Comment by sharyex** [comment]
```
U+FFFD : REPLACEMENT CHARACTER    
U+FFFD : REPLACEMENT CHARACTER  
U+0003 : <control-0003> (END OF TEXT [ETX])  
U+0061 : LATIN SMALL LETTER A  
U+0064 : LATIN SMALL LETTER D  
U+006D : LATIN SMALL LETTER M  
U+0069 : LATIN SMALL LETTER I  
U+006E : LATIN SMALL LETTER N
```
The telnet server is an old simple one part of a larger system, written in C++ and based on the ACE framework. I checked server side and it always receives those 3 characters at the start of the input buffer with this branch straight from the wire, there's no processing done.

Looked at Wireshark and it seems there is a an extra 3 bytes separate request sent before the username:
```
3.501716
[PSH, ACK] Seq=1 Ack=1 Win=262400 Len=3
Data (3 bytes)
Data: ff fd 03

........................

3.604741
[PSH, ACK] Seq=4 Ack=141 Win=262400 Len=6
Data (6 bytes)
Data: 61 64 6d 69 6e 0a (admin + line feed)
[Length: 6]
```

That 3 bytes packet is not sent with the 0.8.1 branch.

**Comment by A9G-Data-Droid** [comment]
Thanks @sharyex ! Wireshark correctly identifies the meaning of that transmission "Do Suppress Go Ahead". That's a TELNET option. Without it, the server is supposed to default to Go Ahead mode which requires software flow control. One of the big changes I made in this version was to support more of the TELNET negotiation sequence. Just enough to tell the server that we are going to proceed in a very basic mode that is similar to how a VT100 terminal would communicate. I needed to add the negotiation logic to connect to an old UNIX server. Any TELNET server that follows the RFCs should be able to handle these options by at least responding with a denial, option not supported. If you are using a custom, non-compliant TELNET server then it won't know what to do. TELNET might largely look like a raw socket but it isn't completely. If you need a raw socket then that's not TELNET. That's just sending raw bits and you don't need a TELNET library to do that.

Can you connect to your server using PUTTY?

**Comment by sharyex** [comment]
Indeed it seems the implementation is not really compliant to any RFC, putty is having issues connecting to it as well. Unfortunately I cannot change anything in the legacy system, so will have to find another solution, was just looking for something fast and easy to use and not bother with implementation details.

Apologies for the troubles, the problem is on my side..

**Comment by A9G-Data-Droid** [comment]
Thanks for the confirmation. If you just need to send pure text use a normal socket:

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=netframework-4.7.2

This Microsoft example gives you all the code you need to connect, send, and receive.

**Comment by 9swampy** [comment]
OMG 4 years later... I've just done a big bump of Net versions so as there's so much breaking in there I put this in too. Anyone complains I'll be pointing them your way for a full explanation...

**Comment by A9G-Data-Droid** [comment]
LoL. Thanks @9swampy . Unfortunately, the project I was using this for stalled. So I'm not using\testing\developing on this right now. It's possible that project could rise from the dead. In the meanwhile, I can try to be helpful as my branch did work when I last used it.

**Pull request closed without merging**
