### PR TITLE
Configurable terminators for TryLogin and TryLoginAsyc

### LINKED ISSUE #25: I need configurable line terminators
My environment doesn't produce a ">" character so all the "TerminatedRead" methods hang open. 
I am expecting a UNIX root shell that ends with "#".

I think that the API should expose a configurable line terminator property that can optionally be set to whatever string the programmer desires.

### PR DESCRIPTION
**Pull request by A9G-Data-Droid**
I noticed that many other terminated functions accept a terminator parameter. 
This PR follows that pattern while defaulting to ">" for backwards compatibility.

Closes #25

### CODE REVIEW

**Comment by 9swampy** [comment]
This looks more like i'd have expected and we've got a green build too. I'd add in a couple of tests though; will take a look tomorrow evening if nothing else crops up. Thx.

**Comment by 9swampy** [comment]
@A9G-Data-Droid one of the nicest things about Git is not needing the end up with commit-revert noise; if you'd combined all three commits to a single or rebase the last I'd have just accepted the PR but as it is I cherry picked as I needed to move things around to follow GitFlow as well. You've still made it in to the codebase though, welcome :)

**Comment by A9G-Data-Droid** [comment]
Thanks! I'm a git noob. I don't know how to combine or rebase.

**Comment by 9swampy** [comment]
Definitely worth finding out; something like TortoiseGit makes all that sort of stuff dead easy unless you're a commandline diehard...

**Pull request closed without merging**
